"""FastAPI entry point: startup, router registration, static files, and pages."""

import os
from urllib.parse import quote
from fastapi import FastAPI, Depends, Request
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, RedirectResponse, JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.config import (
    STATIC_DIR, EVIDENCE_DIR, PDFS_DIR, SYSTEM_VERSION, POLICE_DEPT_NAME
)
from app.seed_data import seed_database
from app.routers import stream, challans, citizen, analytics, simulate, auth, vehicles, reports

app = FastAPI(
    title="Smart Traffic Challan & ANPR System",
    description="Automated Traffic Surveillance, Violation Detection, and E-Challan System",
    version=SYSTEM_VERSION
)

@app.exception_handler(StarletteHTTPException)
async def html_safe_http_exception(request: Request, exc: StarletteHTTPException):
    # Keep API JSON routes returning normal FastAPI error payloads while
    # HTML page routes redirect to the login page instead of exposing the
    # internal pretty-print body above the app shell.
    accept = (request.headers.get("accept") or "").lower()
    is_html_request = "text/html" in accept or request.url.path.endswith(".html")
    if is_html_request:
        location = exc.headers.get("location") if exc.headers else None
        if location:
            return RedirectResponse(url=location, status_code=exc.status_code)

        next_path = request.url.path
        if request.url.query:
            next_path = f"{next_path}?{request.url.query}"
        return RedirectResponse(url=f"/login?next={quote(next_path)}", status_code=307)

    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})

# Allow the browser frontend to call the API during local development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize tables and reference data before the first request.
@app.on_event("startup")
def startup_event():
    print("[System] Initializing Database & Seed Records...")
    seed_database()
    print("[System] Ready to serve.")

# Each router owns one business area and contributes its own /api endpoints.
app.include_router(auth.router)
app.include_router(vehicles.router)
app.include_router(reports.router)
app.include_router(stream.router)
app.include_router(challans.router)
app.include_router(citizen.router)
app.include_router(analytics.router)
app.include_router(simulate.router)

# Evidence and PDFs are generated by the backend but displayed by the frontend.
app.mount("/evidence", StaticFiles(directory=str(EVIDENCE_DIR)), name="evidence")
app.mount("/pdfs", StaticFiles(directory=str(PDFS_DIR)), name="pdfs")

HTML_NO_CACHE = {
    "Cache-Control": "no-store, no-cache, must-revalidate",
    "Pragma": "no-cache",
}


def html_page(filename: str):
    return FileResponse(os.path.join(STATIC_DIR, filename), headers=HTML_NO_CACHE)


# Return the correct HTML page for each user-facing workflow URL.
@app.get("/")
def serve_index():
    return html_page("index.html")

@app.get("/login")
@app.get("/login.html")
def serve_login():
    return html_page("login.html")

@app.get("/register")
@app.get("/register.html")
def serve_register():
    return html_page("register.html")

@app.get("/traffic-rules")
@app.get("/traffic-rules.html")
def serve_traffic_rules():
    return html_page("traffic-rules.html")

@app.get("/dashboard")
@app.get("/dashboard.html")
def serve_dashboard(_: dict = Depends(auth.require_roles_or_redirect("Officer"))):
    return html_page("dashboard.html")

@app.get("/registered-users")
@app.get("/registered-users.html")
def serve_registered_users(_: dict = Depends(auth.require_roles_or_redirect("Officer"))):
    return html_page("registered-users.html")

@app.get("/vehicles")
@app.get("/vehicles/add")
@app.get("/vehicles.html")
def serve_vehicles(_: dict = Depends(auth.require_roles_or_redirect("Officer", "Admin"))):
    return html_page("vehicles.html")

@app.get("/number-plate")
@app.get("/number_plate.html")
def serve_number_plate(_: dict = Depends(auth.require_roles_or_redirect("Citizen", "Officer"))):
    return html_page("number_plate.html")

@app.get("/generate-challan")
@app.get("/generate_challan.html")
def serve_generate_challan(_: dict = Depends(auth.require_roles_or_redirect("Officer"))):
    return html_page("generate_challan.html")

@app.get("/challan/{challan_id}")
def serve_challan_page(challan_id: str, _: dict = Depends(auth.require_roles_or_redirect("Officer"))):
    return html_page("challan_detail.html")

@app.get("/challans")
@app.get("/challans.html")
def serve_challans(_: dict = Depends(auth.require_roles_or_redirect("Officer"))):
    return html_page("challans.html")

@app.get("/reports")
@app.get("/reports.html")
def serve_reports(_: dict = Depends(auth.require_roles_or_redirect("Officer"))):
    return html_page("reports.html")

@app.get("/citizen")
@app.get("/citizen.html")
def serve_citizen():
    return RedirectResponse(url="/number-plate", status_code=302)

@app.get("/simulate.html")
def serve_simulate():
    return RedirectResponse(url="/", status_code=302)

# Expose shared CSS, JavaScript, icons, and other frontend assets.
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app.main:app", host="127.0.0.1", port=8000, reload=True)
